stages:
  - deploy
env:
  stage: .pre
  script:
    - |
        ### include env shell
        . ./sh/env-config.sh;
        ### MAIN Config shell
        if [[ -z "${TARGET_ENV}" || "dev" = ${TARGET_ENV} || "DEV" = "${TARGET_ENV}" ]];
          then export ENV_FILE='.env.dev';
        else
          export ENV_FILE='.env';
        fi
        copy_config 'Authentication' ${ENV_FILE} 'keycloak/';
  tags: 
    - shell
auth:
  stage: deploy
  script:
    - echo 'using file './config' as variable file...'
    - . ./config
    - echo "Starting authentication services..."
    - ls -lart
    - docker-compose -f ./keycloak/auth-dev.yml --env-file=./config up
  tags:
    - shell
    
  
