stages:
  - deploy
env:
  stage: .pre
  script:
    - >
        echo "${TARGET_ENV}"
        if [[ -z "${TARGET_ENV}" || "dev" = ${TARGET_ENV} || "DEV" = "${TARGET_ENV}" ]];
          then export ENV_FILE='.env.dev';
        else
          export ENV_FILE='.env';
        fi
  tags: 
    - shell
auth:
  stage: deploy
  script:
    - echo 'using file '${ENV_FILE}' as variable file...'
    - . ${ENV_FILE}
    - echo "Starting authentication services..."
    - ls -lart
    - docker-compose -f ./keycloak/auth-dev.yml --env-file=${ENV_FILE} up
  tags:
    - shell
    
  
