stages:
  - deploy
env:
  stage: .pre
  script:
    - >
        if [[ -z "${TARGET_ENV}" || "dev" == "${TARGET_ENV}" ]]
          then 
            export ENV_FILE='.env.dev';
        else
          then export ENV_FILE='.env'
        elif
        echo 'using env file '${ENV_FILE}
        .
  tags: 
    - shell
auth:
  stage: deploy
  script:
    - echo "Starting authentication services..."
    - ls -lart
    - docker-compose -f ./keycloak/auth-dev.yml --env-file=${ENV_FILE} up
  tags:
    - shell
    
  