stages:
  - deploy
env:
  stage: .pre
  script:
    - >
        echo ${TARGET_ENV}
        .
  tags: 
    - shell
auth:
  stage: deploy
  script:
    - echo "Starting authentication services..."
    - ls -lart
    - docker-compose -f ./keycloak/auth-dev.yml up
  tags:
    - shell
    
  