version: '3.8'
volumes:
  postgres_data:
    name: ${V_POSTGRES_NAME}
services:
  authBdd:
    image: postgres:${POSTGRES_TAG}
    ports:
      - '5432:5432' 
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_TAG}
    ports:
      - '8080:8080' 
    environment:
      DB_VENDOR: postgres
      DB_ADDR: ${POSTGRES_DB_ADDR}
    links:
      - 'authBdd'