apiVersion: v1
kind: Namespace
metadata:
  name: dev-tool
---
apiVersion: v1
data:
  INSTALL4J_ADD_VM_PARAMS: '-Xms256m -Xmx512m -XX:MaxDirectMemorySize=512m'
kind: ConfigMap
metadata:
  labels:
    app: nexus
  name: nexus-config
  namespace: dev-tool
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: dev-tool
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: 'ingress.nearmi'
      http:
        paths:
          - path: /repo(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: dev-tool
  labels:
    app: nexus
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: nexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: dev-tool
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3
          envFrom:
            - configMapRef:
                name: nexus-config
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
