apiVersion: v1
kind: Namespace
metadata:
  name: nearmi
---  
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-token
  namespace: nearmi
  labels:
    app: keycloak
data:
  KEYCLOAK_USER: YWRtaW4K
  KEYCLOAK_PASSWORD: YWRtaW4K
---
apiVersion: v1
data:
   PROXY_ADDRESS_FORWARDING: "true"
kind: ConfigMap
metadata:
  labels:
    app: keycloak
  name: keycloak-config
  namespace:  nearmi
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: keycloak
  namespace:  nearmi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:
    - host: "ingress.nearmi"
      http:
        paths:
          - path: /keycloak(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: nearmi
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace:  nearmi
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.1
        env:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-token
        ports:
        - name: http
          containerPort: 8080
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
